# .travis.yml

language: node_js
node_js:
  - 6.9.5
deploy:
  provider: heroku
   app: hello1
  api_key:
    secure: "RaDBgGT8n7axDPeTMPpxzu4enEG+6OeeeTYTWV6OuUTUgOezZfmWwUHcnr5Bm55BwkK3bUuYK+SREKiN1QSVNNmKh1pzpvex3W7UOLy477pfzOl/cPOG4gS/Z8ntBE748G+bIHHyK24RbHp3hY9OxTcEjk2Pr/HBHHhyzQbXALzWnPEKLevT/MCeLovlJgSznGKXMknEyqQ/dtoG/8hAS7aORGakYNHQsenZy/9cWRejLqWgsZt1uUIQl9uc0mDUAhIdobhg1a5xPjjt7EZ35yIeo+AyMk2Cse68VtOuckXjGt4nXHTdmw2LdKS4+5U3liq0RnVVxtjGvuAsJqRQczUZ3OKfhghH1tb78kPn/rpmqFkMkBwc3M+oUw0IihVPwcMHtXk/TQWTWQJvLzcTldy7VxAttLY+rKJoY64n9ftZTzqcagYMyYtb4AYFBM8ddmOcRelkZjji3WjWydwJNPbeD2eOBnU13DlMAAaZfthpD1nRYLK7y4IdlYayfM18zrqmglE0fCEPDxglqWTL7tCj17go1rXRDbN2wAO3xwg1XZX/qnvR3/jEgKpdUmewKD8lg8j5zkIm2doZ8U2RLzZVAVNSi7rkp8HY6q5AdMYU/jpUkxNGjGVdvdTT9CsbCi++T2OQJ4BDv6/saRjKEeK/OPPm9mNmtXSnxt3QkGs="
